### ISSUE TITLE
Unknown target for autonumber reference:

### ISSUE THREAD

**Issue by Sandhuanand** [peastman/statmech#1]
When I tried to compile the make html file its showing that 
Exception occurred:
  File "~\statmech-master\source\autonumber.py", line 60, in doctree_resolved
    raise ValueError('Unknown target for autonumber reference: '+target)
ValueError: Unknown target for autonumber reference: Figure,binomial

**Comment by peastman** [comment]
A recent update to Sphinx broke the script I use for generating numbered references.  I've tried to debug it, but haven't figured it out so far.  If you use Sphinx 1.5.6, it works correctly.  Possibly some more recent versions too, but I'm not certain exactly which version it broke in.
