### ISSUE TITLE
make latexpdf works with Python 2, but not Python 3

### ISSUE THREAD

**Issue by tkacvins** [peastman/statmech#3]
I am using macOS Big Sur, which comes with Python 2 and Python 3.  I pip3 installed the sphinx module, but then `make latexpdf` fell over with an error as such

```
sphinx-build -b latex -d build/doctrees   source build/latex
Running Sphinx v3.0.0

Exception occurred:
  File "/Users/tjk/statmech/source/numsec.py", line 50, in setup
    app.override_domain(CustomStandardDomain)
AttributeError: 'Sphinx' object has no attribute 'override_domain'
```
If I used pip2 to install sphinx, then things work as expected and I get a nice PDF file.  Are there any plans to move the documentation generation to Python 3?

**Comment by peastman** [comment]
More likely this is something that has changed in a newer version of Sphinx.  They have an unfortunate tendency to keep breaking their API.  Python 2 is obsolete, so they probably haven't released any versions for it in a while, hence you get an old version.

See what version of Sphinx it installed on Python 2, then try installing that same version on Python 3.  Does it work?

**Comment by tkacvins** [comment]
Installing Sphinx 1.8.5 (which is what was installed for Python 2.7.18) into Python 3.7.3 did the trick.  Closing the issue as I now have a work around.

**Comment by elmbeech** [comment]
Hi @peastman ,

Thank you for writing this book!
I am running python3.9 and had troubles trying to compile a pdf version too.
Installing a sphinx version smaller than 3 did the trick.
```
pip install "sphinx<3"
```
Maybe a note on the README.md file would be helpful for others.

Thank you anyway, Elmar
